# Generated by Django 3.2.2 on 2021-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='age',
        ),
        migrations.AddField(
            model_name='recruit',
            name='name2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
