# Generated by Django 3.2.2 on 2021-05-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_name2_recruit_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='gender',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
