# Generated by Django 3.2.2 on 2021-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_recruit_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
