# Generated by Django 3.2.2 on 2021-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_recruit_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='image',
            field=models.ImageField(default=123, upload_to='post_img/'),
            preserve_default=False,
        ),
    ]
